# Manage unknown locations v2

Find unknown locations for the following countries:

Mexico - done
Vietnam - done
Morocco - done
Laos - done
China - done
Hong Kong - done
Bangladesh - done
Cambodia
Philippines

In [10]:
!pip install openpyxl --q

In [11]:
#import libraries
import pandas as pd

## Explore unknown locations taking Mexico as example:

In [12]:
#download_data_url = 'https://api.resourcetrade.earth/api/rt/2.4/downloads?year=2019&importer=484&category=109&units=value&autozoom=1'
df_imports = pd.read_excel (r'../../datasets/raw/unknown_locations/Mexico-484-109-2019.xlsx', sheet_name='Exporters')
df_imports.head()

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg)
0,76,BRA,Brazil,Latin America and the Caribbean,Natural rubber,2015,0.838,0.062
1,144,LKA,Sri Lanka,Central and Southern Asia,Natural rubber,2015,449.803,53.000
2,156,CHN,China,China,Natural rubber,2015,19.407,1.520
3,203,CZE,Czech Republic,Europe,Natural rubber,2015,0.869,0.017
4,251,FRA,France,Europe,Natural rubber,2015,1.354,0.545

In [14]:
#do the analysis just for one year - year 2019
df_imports_2019 = df_imports[df_imports['Year']==2019]
df_imports_2019.head()

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg)
91,76,BRA,Brazil,Latin America and the Caribbean,Natural rubber,2019,0.987,0.105
92,124,CAN,Canada,Northern America,Natural rubber,2019,NaN,NaN
93,144,LKA,Sri Lanka,Central and Southern Asia,Natural rubber,2019,65.673,32.304
94,156,CHN,China,China,Natural rubber,2019,8.422,0.800
95,170,COL,Colombia,Latin America and the Caribbean,Natural rubber,2019,60.312,42.000

In [15]:
print(f'There are {len(df_imports_2019)} exporters  of natural rubber to Mexico')

There are 23 exporters  of natural rubber to Mexico

In [18]:
df_imports_2019.sort_values?

In [22]:
df_imports_2019_top5 = df_imports_2019.sort_values('Value (1000USD)', ascending=False)[:5]
df_imports_2019_top5

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg)
100,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,55189.2180,34419.740
99,320,GTM,Guatemala,Latin America and the Caribbean,Natural rubber,2019,53914.7120,45460.643
111,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,14641.0066,9855.482
107,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,5964.0354,3944.840
104,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4640.5390,1994.675

We can know the production registered by the FAO in 2019 of natural rubber in Mexico (http://www.fao.org/faostat/en/#data/QC). The FAO also provides information for exports of rubber from Mexico and imports from other countries (http://www.fao.org/faostat/en/#data/TP). With this information we can estimate the percentage of in country production vs the percentage of commodity imported from outsourcing.

In [23]:
# dertermine % of inland production vs % of natural rubber imported for outside country using FAO data
natural_rubber_production_Mexico = 79979
export_quatity = 417
import_quatity = 31478

In [25]:
#obtain weights from import vs export 
Country_production_perct = (export_quatity*100)/natural_rubber_production_Mexico
print(f'The country production is: {Country_production_perct} %')
print(f'The country import is: {100-Country_production_perct}%')

The country production is: 0.5213868640518136 %
The country import is: 99.47861313594818%

#### distribute the volume bought at Mexico between the top 5 producers

Now that we know the top 5 exportes of natural rubber to Mexico and the % of inland production vs the % imported we can distribute the volume purchased by the company x between these countries. 

Lets say that we are buying 766 tonnes of natural rubber in Mexico in a location type unknonw. We can therefore say that:

- 0.5213868640518136% of this 766 tonnes are produced in Mexico
- 99.47861313594818 of this 766 tonnes are produced outside Mexico (mainly in Indonesia, Guatemala, Thailand, Vietnam, Malasya)

Let's compute the weights between these countries:

In [27]:
df_imports_2019_top5

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg)
100,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,55189.2180,34419.740
99,320,GTM,Guatemala,Latin America and the Caribbean,Natural rubber,2019,53914.7120,45460.643
111,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,14641.0066,9855.482
107,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,5964.0354,3944.840
104,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4640.5390,1994.675

In [36]:
#total volume produced in the top 5 exporters

total_value_traders = sum(list(df_imports_2019_top5['Value (1000USD)']))

print(f'The total value is: {total_value_traders}')

weight_list = []
for i in range(0, len(df_imports_2019_top5)):
    row = df_imports_2019_top5.iloc[i]
    value = row['Value (1000USD)']
    weight_value = value/ total_value_traders
    weight_list.append(weight_value)

The total value is: 134349.51099999997

In [39]:
df_imports_2019_top5['weights'] = weight_list
df_imports_2019_top5

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
100,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,55189.2180,34419.740,0.410788
99,320,GTM,Guatemala,Latin America and the Caribbean,Natural rubber,2019,53914.7120,45460.643,0.401302
111,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,14641.0066,9855.482,0.108977
107,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,5964.0354,3944.840,0.044392
104,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4640.5390,1994.675,0.034541

In [59]:
def manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/Mexico-484-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=1,
                            export_quatity=1,
                            import_quantity=1
                           ):
    #download_data_url = 'https://api.resourcetrade.earth/api/rt/2.4/downloads?year=2019&importer=484&category=109&units=value&autozoom=1'
   # path = f"r'{excel_path}'"
    #print(path)
    df_imports = pd.read_excel (excel_path, sheet_name=sheet_name)
    df_imports_year = df_imports[df_imports['Year']==year]
    df_imports_year_top5 = df_imports_year.sort_values(sort_key, ascending=False)[:top_number]
    
    #obtain weights from import vs export 
    if country_production != 0:
        country_production_perct = (export_quatity*100)/country_production
    elif country_production == 0:
        country_production_perct = 0
    print(f'The country production is: {country_production_perct} %')
    print(f'The country import is: {100-country_production_perct}%')
    
    #total volume produced in the top 5 exporters

    total_value_traders = sum(list(df_imports_year_top5[sort_key]))

    #print(f'The total value traders is: {total_value_traders}')

    weight_list = []
    for i in range(0, len(df_imports_year_top5)):
        row = df_imports_year_top5.iloc[i]
        value = row['Value (1000USD)']
        weight_value = value/ total_value_traders
        weight_list.append(weight_value)
    
    df_imports_year_top5['weights'] = weight_list
    
    return df_imports_year_top5

In [53]:
!ls ../../datasets/raw/unknown_locations

Bangladesh-50-109-2019.xlsx  Mexico-484-109-2019.xlsx
Cambodia116-109-2019.xlsx    Morocco-504-109-2019.xlsx
China-156-109-2019.xlsx      Philippines608-109-2019.xlsx
HongKong-344-109-2019.xlsx   vietnam-704-109-2019.xlsx
Laos-418-109-2019.xlsx

In [52]:
#manage unknown mexico
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/Mexico-484-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=79979,
                            export_quatity=417,
                            import_quantity=31478
                           )

The country production is: 0.5213868640518136 %
The country import is: 99.47861313594818%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
100,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,55189.2180,34419.740,0.410788
99,320,GTM,Guatemala,Latin America and the Caribbean,Natural rubber,2019,53914.7120,45460.643,0.401302
111,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,14641.0066,9855.482,0.108977
107,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,5964.0354,3944.840,0.044392
104,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4640.5390,1994.675,0.034541

In [60]:
#manage unknown vietnam
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/vietnam-704-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=1182480,
                            export_quatity=159289,
                            import_quantity=24243
                           )

The country production is: 13.4707563764292 %
The country import is: 86.5292436235708%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
112,116,KHM,Cambodia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,213132.529000,170859.451600,0.533223
125,418,LAO,Lao PDR,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,121676.271200,101404.051000,0.304415
137,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,44265.438500,34441.357200,0.110745
126,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,11426.722509,7702.046391,0.028588
120,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,9204.873400,5786.684830,0.023029

In [62]:
#manage unknown morocco
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/Morocco-504-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=0,
                            export_quatity=0,
                            import_quantity=313
                           )

The country production is: 0 %
The country import is: 100%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
92,724,ESP,Spain,Europe,Natural rubber,2019,928.070980,372.699120,0.609034
91,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,247.206360,142.169055,0.162226
88,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,215.679000,79.822000,0.141536
86,384,CIV,Cote d'Ivoire,Sub-Saharan Africa,Natural rubber,2019,70.437537,39.002308,0.046224
80,144,LKA,Sri Lanka,Central and Southern Asia,Natural rubber,2019,62.447000,17.530000,0.040980

In [64]:
#manage unknown laos
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/Laos-418-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=130000,
                            export_quatity=68895,
                            import_quantity=9
                           )

The country production is: 52.996153846153845 %
The country import is: 47.003846153846155%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
30,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,2557.66495,2137.07222,0.610055
27,392,JPN,Japan,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,1080.99900,70.41100,0.257840
29,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,481.00000,962.00000,0.114728
26,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,48.78000,8.04000,0.011635
25,156,CHN,China,China,Natural rubber,2019,24.07200,34.39100,0.005742

In [66]:
#manage unknown china
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/China-156-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=839909,
                            export_quatity=1716,
                            import_quantity=560346
                           )

The country production is: 0.20430784763587484 %
The country import is: 99.79569215236413%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
217,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,1.617202e+06,1.224707e+06,0.549683
205,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4.571768e+05,3.194704e+05,0.155393
197,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,3.217870e+05,2.234619e+05,0.109375
213,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,3.185118e+05,2.511508e+05,0.108261
203,418,LAO,Lao PDR,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,2.273855e+05,1.867919e+05,0.077288

In [67]:
#manage unknown honkong
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/HongKong-344-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=0,
                            export_quatity=768,
                            import_quantity=379
                           )

The country production is: 0 %
The country import is: 100%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
98,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4195.623000,2981.880000,0.549605
102,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,1495.361290,1109.111170,0.195885
104,842,USA,United States,Northern America,Natural rubber,2019,873.424395,72.232219,0.114414
86,156,CHN,China,China,Natural rubber,2019,736.153707,405.773622,0.096432
96,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,333.319694,212.191300,0.043663

In [69]:
#manage unknown cambodia
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/Cambodia116-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=287600,
                            export_quatity=0,
                            import_quantity=198
                           )

The country production is: 0.0 %
The country import is: 100.0%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
38,704,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,3191.88509,1433.63798,0.614585
39,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,1195.22860,1064.77040,0.230136
35,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,510.21838,263.02030,0.098241
33,156,CHN,China,China,Natural rubber,2019,201.05422,87.30333,0.038712
37,682,SAU,Saudi Arabia,Northern Africa and Western Asia,Natural rubber,2019,95.17800,190.56000,0.018326

In [70]:
manage_unkown_locations(excel_path=r'../../datasets/raw/unknown_locations/Philippines608-109-2019.xlsx', sheet_name='Exporters', sort_key='Value (1000USD)',
                            year = 2019,
                            top_number = 5,
                            country_production=431675,
                            export_quatity=0,
                            import_quantity=468
                           )

The country production is: 0.0 %
The country import is: 100.0%

,Exporter M.49,Exporter ISO3,Exporter,Exporter region,Resource,Year,Value (1000USD),Weight (1000kg),weights
93,702,SGP,Singapore,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,11627.62600,4437.73500,0.357682
96,764,THA,Thailand,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,6559.92062,4277.90995,0.201792
83,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,6061.39800,4023.06700,0.186457
88,458,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4140.90220,2265.91977,0.127380
87,410,KOR,"Korea, Republic",Eastern and South-Eastern Asia (excl. China),Natural rubber,2019,4118.44700,2541.45400,0.126689